### ISSUE TITLE
Show minutes instead of temperature @ boil stage

### ISSUE THREAD

**Issue by matsstaff** [matsstaff/stc1000p-ovbsc#1]
Once mashing is done and boilup is reached, it is not really interesting to show temperature anymore.
It would be better to show time left in boil. 
Maybe during hotbreak, show boil time + time left for hot break?

**Comment by kokangit** [comment]
Yes,, that sounds logical!

**Comment by matsstaff** [comment]
Fixed. Also show time left during strike delay.
