### ISSUE TITLE
User defined pump on/off variables

### ISSUE THREAD

**Issue by Kalsta** [matsstaff/stc1000p-ovbsc#10]
Currently you have two options:

   1. Automatic - which has preset pump on/off settings which are non-editable
   2. Manual - pump on/off status is controlled via toggle switch

Possible future firmware upgrade to introduce pump status "Pst" variable which could be toggled on/off during the initial mash (steeping) step, between each mash step (for improved rise time), and during hot break, and at flame out (for trub separation - whirlpooling).

**Comment by matsstaff** [comment]
Agreed. See issue #8.

**Comment by Kalsta** [comment]
Feel free to fold it into issue #8 or close this one entirely, I was only offering a suggestion, you have done a great job so far. 

I currently have both this on my Grainfather and the stc1000p on my fermentation fridge, and would love to say thank you with a small donation?

Cheers,

Kal

**Comment by matsstaff** [comment]
Nice :)
I'll just leave this issue open, as #8 really isn't the same thing.
Haven't had any time during the summer to do anything on the stc-1000+ projects, but I hope that I can polish OVBSC a bit during this fall.
If you want to make me happy with a donation, then please donate to some worthy cause instead (I'd be extra happy if it is for the benefit of children).
Cheers and thanks for the support!
//mats

**Comment by Kalsta** [comment]
You are a nobel and generous man, I already donate to a few worthy charities, but I will make an additional donation on your behalf. Looking forward to seeing the polish on the OVBSC version, as the initial version is great.

**Comment by matsstaff** [comment]
done
