### ISSUE TITLE
Parameter to control pump during mashsteps

### ISSUE THREAD

**Issue by matsstaff** [matsstaff/stc1000p-ovbsc#8]
Like mebbe don't run the pump when temp at or above target. To limit the amount of pumping a bit. Perhaps a timeout?

**Comment by Kalsta** [comment]
Another possibility would be to make Pump Duration "Pdu" available if "Pst" (#10) is set to "1" (on). Pdu could then be expressed as a percentage of that step (1-100%) eg. if hot break duration is 20 mins and Pst=1 & Pdu=25 then pump is on for first 5 mins of hot break then switches off?

**Comment by matsstaff** [comment]
Closing this. It would be difficult to do something 'good' I think. And #10 does as lot of good anyway.
